// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomessDocumentDataSlicesSlice = InformacoesSlice;

/**
 * Content for Homess documents
 */
interface HomessDocumentData {
  /**
   * TITULO field in *Homess*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * turis field in *Homess*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.turis
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  turis: prismic.RichTextField;

  /**
   * SOBRE NÓS field in *Homess*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.sobre_nos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sobre_nos: prismic.RichTextField;

  /**
   * Viagens field in *Homess*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.viagens
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  viagens: prismic.KeyTextField;

  /**
   * VIAGEM 1 field in *Homess*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.viagem_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  viagem_1: prismic.ImageField<never>;

  /**
   * descricao viagem 1 field in *Homess*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.descricao_viagem_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao_viagem_1: prismic.RichTextField;

  /**
   * viagem 22 field in *Homess*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.viagem_22
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  viagem_22: prismic.KeyTextField;

  /**
   * VIAGEM 2 field in *Homess*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.viagem_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  viagem_2: prismic.ImageField<never>;

  /**
   * descricao viagem 2 field in *Homess*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.descricao_viagem_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao_viagem_2: prismic.RichTextField;

  /**
   * viagem 33 field in *Homess*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.viagem_33
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  viagem_33: prismic.KeyTextField;

  /**
   * VIAGEM 3 field in *Homess*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.viagem_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  viagem_3: prismic.ImageField<never>;

  /**
   * descricao viagem 3 field in *Homess*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.descricao_viagem_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao_viagem_3: prismic.RichTextField;

  /**
   * Slice Zone field in *Homess*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homess.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomessDocumentDataSlicesSlice>;
}

/**
 * Homess document from Prismic
 *
 * - **API ID**: `homess`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomessDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomessDocumentData>, "homess", Lang>;

/**
 * Content for Sobre_nos documents
 */
interface SobreNosDocumentData {
  /**
   * SOBRE_NOS field in *Sobre_nos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.sobre_nos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sobre_nos: prismic.KeyTextField;

  /**
   * descricao field in *Sobre_nos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;

  /**
   * descricao1 field in *Sobre_nos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.descricao1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao1: prismic.RichTextField;

  /**
   * descricao2 field in *Sobre_nos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.descricao2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao2: prismic.RichTextField;

  /**
   * descricao3 field in *Sobre_nos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.descricao3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao3: prismic.RichTextField;

  /**
   * descricao4 field in *Sobre_nos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.descricao4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao4: prismic.RichTextField;

  /**
   * descricao5 field in *Sobre_nos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.descricao5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao5: prismic.RichTextField;

  /**
   * descricao6 field in *Sobre_nos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.descricao6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao6: prismic.RichTextField;

  /**
   * imagem turistio field in *Sobre_nos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.imagem_turistio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_turistio: prismic.ImageField<never>;

  /**
   * INÍCIO field in *Sobre_nos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.inicio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  inicio: prismic.KeyTextField;
}

/**
 * Sobre_nos document from Prismic
 *
 * - **API ID**: `sobre_nos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SobreNosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SobreNosDocumentData>,
    "sobre_nos",
    Lang
  >;

export type AllDocumentTypes = HomessDocument | SobreNosDocument;

/**
 * Default variation for Home Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Home*
 */
type HomeSliceVariation = HomeSliceDefault;

/**
 * Home Shared Slice
 *
 * - **API ID**: `home`
 * - **Description**: Home
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSlice = prismic.SharedSlice<"home", HomeSliceVariation>;

/**
 * Default variation for Informacoes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformacoesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Informacoes*
 */
type InformacoesSliceVariation = InformacoesSliceDefault;

/**
 * Informacoes Shared Slice
 *
 * - **API ID**: `informacoes`
 * - **Description**: Informacoes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformacoesSlice = prismic.SharedSlice<
  "informacoes",
  InformacoesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomessDocument,
      HomessDocumentData,
      HomessDocumentDataSlicesSlice,
      SobreNosDocument,
      SobreNosDocumentData,
      AllDocumentTypes,
      HomeSlice,
      HomeSliceVariation,
      HomeSliceDefault,
      InformacoesSlice,
      InformacoesSliceVariation,
      InformacoesSliceDefault,
    };
  }
}
